services:
  app:
    build: .
    container_name: rate-limiting-scraper-prod
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
