services:
  app:
    build: .
    container_name: rate-limiting-scraper-prod
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: rate-limiting-scraper-redis-prod
    ports:
      - "6379:6379"
    restart: unless-stopped
