services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rate-limiting-scraper-dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env
    depends_on:
      - redis
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: rate-limiting-scraper-test
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.test.json:/app/tsconfig.test.json
      - ./jest.config.js:/app/jest.config.js
      - ./.env:/app/.env
    depends_on:
      - redis
    command: npm test

  redis:
    image: redis:7-alpine
    container_name: rate-limiting-scraper-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped
