services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rate-limiting-scraper-dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env
    restart: unless-stopped
